### PR TITLE
Gracefully handle `Error` instances without a `stack` property

### LINKED ISSUE #6: message generation breaks when AbortError/Error without stack is encountered
Hi,

I’m not quite sure if this is a bug that should be handled here or in the clean-stack lib, but when using abortable fetch requests on ArchLinux with Chromium 72.0.3626.96 a `DOMException`/`AbortError` is thrown that, even though it is an instance of `Error`, does not have a stack (it’s simply `undefined`). I’ve yet to confirm if this is standard-compliant and/or happens in other browsers but for the sake of being robust I think it would be a good idea to actually check if `err.stack` exists during the generation of `message`.

Example ([bundled version](https://github.com/sindresorhus/aggregate-error/files/2866033/stack_error.zip)):

```js
import AggregateError from 'aggregate-error'

const { fetch, AbortController } = window
const controller = new AbortController()
const signal = controller.signal

fetch('https://api.github.com/', { signal })
  .then(res => res.json())
  .then(data => { console.info(data) })
  .catch(err => Promise.reject(new AggregateError([new Error('something went south during github api request'), err]))

controller.abort()
```
cheers Konrad

### PR DESCRIPTION
**Pull request by kmohrf**
This fixes #6. I’ve added a test and included some documentation why the stack property is checked.

I thought about simply casting `error.stack` to a string, but that didn’t seem like a good idea (who knows if there are more fun exceptions to the `stack` property like array values). So I ended up with validating it as a string or String object (both of which implement `replace`, so that should be fine).

Feel free to change anything to your liking!

Thanks!

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -11,7 +12,10 @@ class AggregateError extends Error {
 		}
 
 		errors = [...errors].map(error => {
-			if (error instanceof Error) {
+			// Unfortunately stack is not standardized as a property of Error instances
+			// which makes it necessary to explicitly check for it and its type.
+			// Error instances without a stack should be handled as plain objects
+			if (error instanceof Error && isString(error.stack)) {
```
Comment (sindresorhus) [inline index.js]: `typeof value === 'string'` is enough. The stack can never be a Object-wrapped string.

File: test.js [hunk 2]
```diff
@@ -11,18 +17,21 @@ test('main', t => {
...
-		}
+		},
+		createStacklessError()
 	]);
 
 	console.log(error);
 
 	t.regex(error.message, /Error: foo\n {8}at /);
 	t.regex(error.message, /Error: bar\n {8}at /);
+	t.regex(error.message, /Error: stackless\n {8}at /);
```
Comment (sindresorhus) [inline test.js]: Create a new test for this.

File: index.js (hunk 1 above)
Comment (sindresorhus) [reply index.js]: Also, this way, it will lose information about error type. I would consider a better way to handle this.

**Comment by kmohrf** [comment]
> `typeof value === 'string'` is enough. The stack can never be a Object-wrapped string.

With `stack` not being standardized it seems to me that it’s as likely a `String` object as it is `undefined`. I don’t see the point of omitting that specific case if support for it is already there.

> Also, this way, it will lose information about error type. I would consider a better way to handle this.

I agree and have changed the implementation. If you still have something else in mind, please consider a more detailed expectation.

File: index.js (hunk 1 above)
Comment (kmohrf) [reply index.js]: didn’t know that github keeps reviewed but outdated code in place. see below for an answer.

**Comment by kmohrf** [comment]
any further thoughts @sindresorhus?

**Comment by sindresorhus** [comment]
Thanks :)
